apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-web-server
  name: my-web-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-server
  template:
    metadata:
      labels:
        app: my-web-server
    spec:
      containers:
      - image: edgarrr/my-web-server
        imagePullPolicy: Always
        name: my-web-server
        ports:
        - containerPort: 80
          protocol: TCP
