kind: Service
apiVersion: v1
metadata:
  name: my-web-server
  labels:
    app: my-web-server
spec:
  selector:
    app: my-web-server
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
